### ISSUE TITLE
Duplicate variable declaration, "sectionObject" already set!

### ISSUE THREAD

**Issue by typo3ua** [sotastudio/TYPO3.Extbase.SocialSharingPrivacy#1]
Hello, all!
- I included static Extension Template
- I inserted a сontent element "Social Share Privacy" (Frontend Plugin) on my page "My page".
- I Checked the Frontend!

I get an error:

Duplicate variable declaration, "sectionObject" already set!

Why? What have I done wrong?

**Comment by andyhausmann** [comment]
Doh - sounds bad!

I've already pushed an update to TER this morning. Let's take a look at this tomorrow - if the update didn't resolve this issue.

Though I obviously never checked the Frontend Plugin... :-1: 

In most cases I copied the TypoScript Object in a library and outputted it within the template.
The Social Sharing Privacy Object is waiting for you at "temp.socialSharingPrivacy".

In the meanwhile, i will check your issue.

**Comment by typo3ua** [comment]
Yes, thanks ... but I need only "Frontend Plugin"
I will wait for updates.

**Comment by andyhausmann** [comment]
Understood. I already checked the Frontend Plugin - worked like a charm.

Please provide further details regarding your issue:
- Version of TYPO3
- Version of EXT:extbase
- Version of EXT:fluid
- Version of EXT:helperkit
- Version of EXT:vhs
- how you did implement jQuery into your website - EXT:t3jquery?

**Comment by typo3ua** [comment]
# I use:

TYPO3 6.1.3 / PHP 5.4.7
Extbase Framework for Extensions 6.1.0
Fluid Templating Engine 6.1.0
Fluid Content Engine 3.1.0
Fluid Pages Engine 2.1.0
Flux: Fluid FlexForms 6.0.1
VHS: Fluid ViewHelpers 1.8.1
Social Share Privacy 1.1.1

... jquery through [includeJSFooter] and [includeJSlibs]

# I do not use:

helperkit
t3jquery

Dependencies TYPO3 (6.0.0 - 6.0.99), extbase (1.3.0), fluid (1.3.0)  ..... Meets current settings

**Comment by andyhausmann** [comment]
I am not sure but it looks like the Extension Uploader did its bit of magic and removed the constraint/dependency to EXT:helperkit. Please install helperkit and check whether it's running now.

If it does not, please let me throw a look into your installation so I can clear things up for myself. You'll find my email address... everywhere.

**Comment by typo3ua** [comment]
:+1:  Now everything is working well

Thanks!

**Comment by andyhausmann** [comment]
Glad to hear that.
