### ISSUE TITLE
Using temp.socialSharingPrivacy not working

### ISSUE THREAD

**Issue by derpepe** [sotastudio/TYPO3.Extbase.SocialSharingPrivacy#6]
I try to use temp.socialSharingPrivacy as defined in your setup.txt.

I use it like this:
  page.30 < temp.socialSharingPrivacy

And I get the error
  The default controller for extension "SocialSharingPrivacy" and plugin "Pi1" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.

**Comment by andyhausmann** [comment]
Ah, sorry. Instead of Pi1, use Base.

temp.socialSharingPrivacy = USER
temp.socialSharingPrivacy {
    userFunc = tx_extbase_core_bootstrap->run
    pluginName = Base
    extensionName = SocialSharingPrivacy
    controller = SocialSharingPrivacy
    action = index
    switchableControllerActions {
        SocialSharingPrivacy {
            1 = index
        }
    }
    settings =< plugin.tx_socialsharingprivacy.settings
    view =< plugin.tx_socialsharingprivacy.view
}

**Comment by andyhausmann** [comment]
Just forgot to adjust that. I'll fix it asap and provide an update.

**Comment by derpepe** [comment]
Thank you for the fast reply.

But this leads to another error:
  Could not analyse class:Tx_SocialSharingPrivacy_Controller_SocialSharingPrivacyController maybe not loaded or no autoloader?

**Comment by andyhausmann** [comment]
Arrr...!

Okay, this happens due to the Namespaces. Try:

temp.socialSharingPrivacy = USER
temp.socialSharingPrivacy {
userFunc = tx_extbase_core_bootstrap->run
pluginName = Base
extensionName = SotaStudio.SocialSharingPrivacy
controller = SocialSharingPrivacy
action = index
switchableControllerActions {
SocialSharingPrivacy {
1 = index
}
}
settings =< plugin.tx_socialsharingprivacy.settings
view =< plugin.tx_socialsharingprivacy.view
}

**Comment by derpepe** [comment]
"ReflectionData_SotaStudio.SocialSharingPrivacy" is not a valid cache entry identifier. ;)

**Comment by andyhausmann** [comment]
You may need to clear the Caches in typo3temp/Cache.

**Comment by andyhausmann** [comment]
If it does not solve it, i will check this one later on.

**Comment by derpepe** [comment]
Clearing typo3temp/Cache doesn't solve the issue, sorry. :/

**Comment by andyhausmann** [comment]
temp.socialSharingPrivacy = USER
temp.socialSharingPrivacy {
userFunc = tx_extbase_core_bootstrap->run
vendorName = SotaStudio
pluginName = Base
extensionName = SocialSharingPrivacy
controller = SocialSharingPrivacy
action = index
switchableControllerActions {
SocialSharingPrivacy {
1 = index
}
}
settings =< plugin.tx_socialsharingprivacy.settings
view =< plugin.tx_socialsharingprivacy.view
}

**Comment by derpepe** [comment]
Cool, works for me :)
Thank you :+1:

**Comment by andyhausmann** [comment]
You are very welcome! If you are happy, i am as well! :)

**Comment by andyhausmann** [comment]
SHA: 7ce39e287551e4b6dd852993cdc88eab79bef557
